name: vscreen_client_core
description: this is vscreen client core implementation
homepage: https://github.com/vscreen
version: 0.1.2
authors:
  - Lukas Herman <lherman.cs@gmail.com>
dependencies:
  web_socket_channel: ^1.0.9
environment:
    sdk: ">=1.8.0 <3.0.0"