name: vscreen_client_core
description: this is vscreen client core implementation
homepage: https://github.com/vscreen
version: 0.1.4
authors:
  - Lukas Herman <lherman.cs@gmail.com>
dependencies:
  grpc:
  protobuf:
environment:
    sdk: ">=1.8.0 <3.0.0"